[package]
name = "dicediele"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.18"
eframe = "0.19.0"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.6.0"
