var sourcesIndex = JSON.parse('{\
"ab_glyph":["",[["ttfp",[],["outliner.rs","variable.rs"]]],["codepoint_ids.rs","err.rs","font.rs","font_arc.rs","glyph.rs","lib.rs","outlined.rs","scale.rs","ttfp.rs","variable.rs"]],\
"ab_glyph_rasterizer":["",[],["geometry.rs","lib.rs","raster.rs"]],\
"ahash":["",[],["convert.rs","fallback_hash.rs","hash_map.rs","hash_set.rs","lib.rs","operations.rs","random_state.rs","specialize.rs"]],\
"aho_corasick":["",[["packed",[["teddy",[],["compile.rs","mod.rs","runtime.rs"]]],["api.rs","mod.rs","pattern.rs","rabinkarp.rs","vector.rs"]]],["ahocorasick.rs","automaton.rs","buffer.rs","byte_frequencies.rs","classes.rs","dfa.rs","error.rs","lib.rs","nfa.rs","prefilter.rs","state_id.rs"]],\
"arboard":["",[],["common.rs","lib.rs","windows_clipboard.rs"]],\
"atty":["",[],["lib.rs"]],\
"bitflags":["",[],["lib.rs"]],\
"bytemuck":["",[],["anybitpattern.rs","checked.rs","contiguous.rs","internal.rs","lib.rs","no_uninit.rs","offset_of.rs","pod.rs","pod_in_option.rs","transparent.rs","zeroable.rs","zeroable_in_option.rs"]],\
"bytemuck_derive":["",[],["lib.rs","traits.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"clap":["",[["builder",[],["action.rs","app_settings.rs","arg.rs","arg_group.rs","arg_predicate.rs","arg_settings.rs","command.rs","debug_asserts.rs","mod.rs","os_str.rs","possible_value.rs","range.rs","resettable.rs","str.rs","styled_str.rs","value_hint.rs","value_parser.rs"]],["error",[],["context.rs","format.rs","kind.rs","mod.rs"]],["output",[["textwrap",[],["core.rs","mod.rs"]]],["fmt.rs","help.rs","help_template.rs","mod.rs","usage.rs"]],["parser",[["features",[],["mod.rs","suggestions.rs"]],["matches",[],["any_value.rs","arg_matches.rs","matched_arg.rs","mod.rs","value_source.rs"]]],["arg_matcher.rs","error.rs","mod.rs","parser.rs","validator.rs"]],["util",[],["color.rs","flat_map.rs","flat_set.rs","graph.rs","id.rs","mod.rs","str_to_bool.rs"]]],["derive.rs","lib.rs","macros.rs","mkeymap.rs"]],\
"clap_lex":["",[],["lib.rs"]],\
"clipboard_win":["",[],["formats.rs","lib.rs","raw.rs","utils.rs"]],\
"cty":["",[],["lib.rs"]],\
"dicediele":["",[["gui",[],["mod.rs"]],["terminal",[],["mod.rs"]]],["lib.rs","probabilities.rs","rolls.rs"]],\
"eframe":["",[["native",[],["epi_integration.rs","mod.rs","run.rs"]]],["epi.rs","lib.rs"]],\
"egui":["",[["containers",[],["area.rs","collapsing_header.rs","combo_box.rs","frame.rs","mod.rs","panel.rs","popup.rs","resize.rs","scroll_area.rs","window.rs"]],["data",[],["input.rs","mod.rs","output.rs"]],["input_state",[],["touch_state.rs"]],["util",[],["cache.rs","fixed_cache.rs","history.rs","id_type_map.rs","mod.rs","undoer.rs"]],["widgets",[["plot",[["items",[],["bar.rs","box_elem.rs","mod.rs","rect_elem.rs","values.rs"]]],["legend.rs","mod.rs","transform.rs"]],["text_edit",[],["builder.rs","cursor_range.rs","mod.rs","output.rs","state.rs","text_buffer.rs"]]],["button.rs","color_picker.rs","drag_value.rs","hyperlink.rs","image.rs","label.rs","mod.rs","progress_bar.rs","selected_label.rs","separator.rs","slider.rs","spinner.rs"]]],["animation_manager.rs","context.rs","frame_state.rs","grid.rs","id.rs","input_state.rs","introspection.rs","layers.rs","layout.rs","lib.rs","memory.rs","menu.rs","painter.rs","placer.rs","response.rs","sense.rs","style.rs","ui.rs","widget_text.rs"]],\
"egui_glow":["",[],["lib.rs","misc_util.rs","painter.rs","post_process.rs","shader_version.rs","vao.rs"]],\
"egui_winit":["",[],["clipboard.rs","lib.rs","screen_reader.rs","window_settings.rs"]],\
"emath":["",[],["align.rs","lib.rs","numeric.rs","pos2.rs","rect.rs","rect_transform.rs","rot2.rs","smart_aim.rs","vec2.rs"]],\
"epaint":["",[["text",[],["cursor.rs","font.rs","fonts.rs","mod.rs","text_layout.rs","text_layout_types.rs"]],["util",[],["mod.rs","ordered_float.rs"]]],["bezier.rs","color.rs","image.rs","lib.rs","mesh.rs","mutex.rs","shadow.rs","shape.rs","shape_transform.rs","stats.rs","stroke.rs","tessellator.rs","texture_atlas.rs","texture_handle.rs","textures.rs"]],\
"error_code":["",[],["lib.rs","posix.rs","system.rs"]],\
"form_urlencoded":["",[],["lib.rs"]],\
"getrandom":["",[],["error.rs","error_impls.rs","lib.rs","util.rs","windows.rs"]],\
"glow":["",[],["gl46.rs","lib.rs","native.rs","version.rs"]],\
"glutin":["",[["api",[["egl",[],["make_current_guard.rs","mod.rs"]],["wgl",[],["make_current_guard.rs","mod.rs"]]],["dlloader.rs","mod.rs"]],["platform",[],["mod.rs","windows.rs"]],["platform_impl",[["windows",[],["mod.rs"]]],["mod.rs"]]],["context.rs","lib.rs","windowed.rs"]],\
"glutin_egl_sys":["",[],["lib.rs"]],\
"glutin_wgl_sys":["",[],["lib.rs"]],\
"idna":["",[],["lib.rs","punycode.rs","uts46.rs"]],\
"instant":["",[],["lib.rs","native.rs"]],\
"lazy_static":["",[],["inline_lazy.rs","lib.rs"]],\
"libc":["",[["windows",[["msvc",[],["mod.rs"]]],["mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"libloading":["",[["os",[["windows",[],["mod.rs"]]],["mod.rs"]]],["changelog.rs","error.rs","lib.rs","safe.rs","util.rs"]],\
"lock_api":["",[],["lib.rs","mutex.rs","remutex.rs","rwlock.rs"]],\
"log":["",[],["lib.rs","macros.rs"]],\
"memchr":["",[["memchr",[["x86",[],["avx.rs","mod.rs","sse2.rs"]]],["fallback.rs","iter.rs","mod.rs","naive.rs"]],["memmem",[["prefilter",[["x86",[],["avx.rs","mod.rs","sse.rs"]]],["fallback.rs","genericsimd.rs","mod.rs"]],["x86",[],["avx.rs","mod.rs","sse.rs"]]],["byte_frequencies.rs","genericsimd.rs","mod.rs","rabinkarp.rs","rarebytes.rs","twoway.rs","util.rs","vector.rs"]]],["cow.rs","lib.rs"]],\
"memoffset":["",[],["lib.rs","offset_of.rs","raw_field.rs","span_of.rs"]],\
"nohash_hasher":["",[],["lib.rs"]],\
"once_cell":["",[],["imp_std.rs","lib.rs","race.rs"]],\
"os_str_bytes":["",[["windows",[["wtf8",[],["code_points.rs","convert.rs","mod.rs","string.rs"]]],["mod.rs","raw.rs"]]],["iter.rs","lib.rs","pattern.rs","raw_str.rs","util.rs"]],\
"owned_ttf_parser":["",[],["convert.rs","lib.rs","owned.rs","preparse.rs"]],\
"parking_lot":["",[],["condvar.rs","deadlock.rs","elision.rs","fair_mutex.rs","lib.rs","mutex.rs","once.rs","raw_fair_mutex.rs","raw_mutex.rs","raw_rwlock.rs","remutex.rs","rwlock.rs","util.rs"]],\
"parking_lot_core":["",[["thread_parker",[["windows",[],["keyed_event.rs","mod.rs","waitaddress.rs"]]],["mod.rs"]]],["lib.rs","parking_lot.rs","spinwait.rs","util.rs","word_lock.rs"]],\
"percent_encoding":["",[],["lib.rs"]],\
"pin_project_lite":["",[],["lib.rs"]],\
"ppv_lite86":["",[["x86_64",[],["mod.rs","sse2.rs"]]],["lib.rs","soft.rs","types.rs"]],\
"proc_macro2":["",[],["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"rand":["",[["distributions",[],["bernoulli.rs","distribution.rs","float.rs","integer.rs","mod.rs","other.rs","slice.rs","uniform.rs","utils.rs","weighted.rs","weighted_index.rs"]],["rngs",[["adapter",[],["mod.rs","read.rs","reseeding.rs"]]],["mock.rs","mod.rs","std.rs","thread.rs"]],["seq",[],["index.rs","mod.rs"]]],["lib.rs","prelude.rs","rng.rs"]],\
"rand_chacha":["",[],["chacha.rs","guts.rs","lib.rs"]],\
"rand_core":["",[],["block.rs","error.rs","impls.rs","le.rs","lib.rs","os.rs"]],\
"raw_window_handle":["",[],["android.rs","appkit.rs","haiku.rs","lib.rs","redox.rs","uikit.rs","unix.rs","web.rs","windows.rs"]],\
"regex":["",[["literal",[],["imp.rs","mod.rs"]]],["backtrack.rs","compile.rs","dfa.rs","error.rs","exec.rs","expand.rs","find_byte.rs","input.rs","lib.rs","pikevm.rs","pool.rs","prog.rs","re_builder.rs","re_bytes.rs","re_set.rs","re_trait.rs","re_unicode.rs","sparse.rs","utf8.rs"]],\
"regex_syntax":["",[["ast",[],["mod.rs","parse.rs","print.rs","visitor.rs"]],["hir",[["literal",[],["mod.rs"]]],["interval.rs","mod.rs","print.rs","translate.rs","visitor.rs"]],["unicode_tables",[],["age.rs","case_folding_simple.rs","general_category.rs","grapheme_cluster_break.rs","mod.rs","perl_word.rs","property_bool.rs","property_names.rs","property_values.rs","script.rs","script_extension.rs","sentence_break.rs","word_break.rs"]]],["either.rs","error.rs","lib.rs","parser.rs","unicode.rs","utf8.rs"]],\
"scopeguard":["",[],["lib.rs"]],\
"smallvec":["",[],["lib.rs"]],\
"str_buf":["",[],["lib.rs"]],\
"strsim":["",[],["lib.rs"]],\
"syn":["",[["gen",[],["clone.rs","gen_helper.rs"]]],["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]],\
"termcolor":["",[],["lib.rs"]],\
"thiserror":["",[],["aserror.rs","display.rs","lib.rs"]],\
"thiserror_impl":["",[],["ast.rs","attr.rs","expand.rs","fmt.rs","generics.rs","lib.rs","prop.rs","valid.rs"]],\
"tinyvec":["",[["array",[],["generated_impl.rs"]]],["array.rs","arrayvec.rs","arrayvec_drain.rs","lib.rs","slicevec.rs","tinyvec.rs"]],\
"tinyvec_macros":["",[],["lib.rs"]],\
"tracing":["",[],["dispatcher.rs","field.rs","instrument.rs","level_filters.rs","lib.rs","macros.rs","span.rs","stdlib.rs","subscriber.rs"]],\
"tracing_core":["",[],["callsite.rs","dispatcher.rs","event.rs","field.rs","lazy.rs","lib.rs","metadata.rs","parent.rs","span.rs","stdlib.rs","subscriber.rs"]],\
"ttf_parser":["",[["ggg",[],["chained_context.rs","context.rs","feature_variations.rs","layout_table.rs","lookup.rs","mod.rs"]],["tables",[["cff",[],["argstack.rs","cff1.rs","cff2.rs","charset.rs","charstring.rs","dict.rs","encoding.rs","index.rs","mod.rs","std_names.rs"]],["cmap",[],["format0.rs","format10.rs","format12.rs","format13.rs","format14.rs","format2.rs","format4.rs","format6.rs","mod.rs"]]],["ankr.rs","avar.rs","cbdt.rs","cblc.rs","feat.rs","fvar.rs","gdef.rs","glyf.rs","gpos.rs","gsub.rs","gvar.rs","head.rs","hhea.rs","hmtx.rs","hvar.rs","kern.rs","kerx.rs","loca.rs","math.rs","maxp.rs","mod.rs","morx.rs","mvar.rs","name.rs","os2.rs","post.rs","sbix.rs","svg.rs","trak.rs","vhea.rs","vorg.rs"]]],["aat.rs","lib.rs","parser.rs","var_store.rs"]],\
"unicode_bidi":["",[["char_data",[],["mod.rs","tables.rs"]]],["data_source.rs","deprecated.rs","explicit.rs","format_chars.rs","implicit.rs","level.rs","lib.rs","prepare.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"unicode_normalization":["",[],["__test_api.rs","decompose.rs","lib.rs","lookups.rs","no_std_prelude.rs","normalize.rs","perfect_hash.rs","quick_check.rs","recompose.rs","replace.rs","stream_safe.rs","tables.rs"]],\
"url":["",[],["host.rs","lib.rs","origin.rs","parser.rs","path_segments.rs","quirks.rs","slicing.rs"]],\
"webbrowser":["",[],["lib.rs","windows.rs"]],\
"widestring":["",[["platform",[],["mod.rs","windows.rs"]]],["error.rs","iter.rs","lib.rs","ucstr.rs","ucstring.rs","ustr.rs","ustring.rs"]],\
"winapi":["",[["km",[],["mod.rs"]],["shared",[],["basetsd.rs","cfg.rs","devpropdef.rs","guiddef.rs","ktmtypes.rs","minwindef.rs","mod.rs","ntdef.rs","ntstatus.rs","rpc.rs","rpcdce.rs","rpcndr.rs","windef.rs","winerror.rs","wtypes.rs","wtypesbase.rs"]],["ucrt",[],["mod.rs"]],["um",[["gl",[],["mod.rs"]]],["cfgmgr32.rs","combaseapi.rs","consoleapi.rs","errhandlingapi.rs","fileapi.rs","libloaderapi.rs","minwinbase.rs","mod.rs","oaidl.rs","objbase.rs","objidl.rs","objidlbase.rs","processenv.rs","processthreadsapi.rs","propidl.rs","reason.rs","shellapi.rs","stringapiset.rs","synchapi.rs","unknwnbase.rs","winbase.rs","wincon.rs","wincontypes.rs","wingdi.rs","winnls.rs","winnt.rs","winreg.rs","winuser.rs"]],["vc",[],["excpt.rs","limits.rs","mod.rs","vadefs.rs","vcruntime.rs"]],["winrt",[],["mod.rs"]]],["lib.rs","macros.rs"]],\
"winapi_util":["",[],["console.rs","file.rs","lib.rs","win.rs"]],\
"windows_x86_64_msvc":["",[],["lib.rs"]],\
"winit":["",[["platform",[],["mod.rs","run_return.rs","windows.rs"]],["platform_impl",[["windows",[["event_loop",[],["runner.rs"]]],["dark_mode.rs","definitions.rs","dpi.rs","drop_handler.rs","event.rs","event_loop.rs","icon.rs","ime.rs","mod.rs","monitor.rs","raw_input.rs","util.rs","window.rs","window_state.rs"]]],["mod.rs"]]],["dpi.rs","error.rs","event.rs","event_loop.rs","icon.rs","lib.rs","monitor.rs","window.rs"]]\
}');
createSourceSidebar();
